name: Manual NPM Release
on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      
      - name: Install NodeJS v21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'npm'

      - name: Install
        run:  nix run .#install

      - name: Build
        run:  nix run .#build

      - run: |
          git config --global user.email "${{ secrets.CI_GIT_EMAIL }}"
          git config --global user.name "${{ secrets.CI_GIT_USER }}"

      # bump version
      - name: Bump Patch Version
        run: echo "NEW_VERSION=$(npm version patch --no-git-tag-version)" >> $GITHUB_ENV

      # Commit changes and tag
      - name: Commit And Tag
        run: |
          git add "package.json"
          git add "package-lock.json"
          git commit -m "Release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      # Push the commit to remote
      - name: Push Changes To Remote
        run: | 
          git push origin 
          git push -u origin ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create zip and tar built package archives for GH release
      - name: Create Built Package Archives
        run: | 
          zip -r rainlang-codemirror-${{ env.NEW_VERSION }}.zip dist src README.md package.json
          tar -czvf rainlang-codemirror-${{ env.NEW_VERSION }}.tar.gz dist src README.md package.json

      # Create gitHub release with built package archives
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          # specify the additional built packages to be included in GH release
          files: |
            rainlang-codemirror-${{ env.NEW_VERSION }}.zip
            rainlang-codemirror-${{ env.NEW_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish To NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public