name: Rainix CI
on: [push]

jobs:
  rainix:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      DEPLOYMENT_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: rainlanguage/rainix/.github/actions/nix-cachix-setup@main
        with:
          checkout: 'false'
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install
        run:  nix develop -c npm install

      - name: Build
        run:  nix develop -c npm run build
      
      - name: Run Tests
        run:  nix develop -c npm test